<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Home Page</title>
</head>
<body>

 <div class="row">
            <div class="col-12">
                <div class="tm-main-bg">
                       <div class="grid tm-carousel">
                      
                     <!--   <img alt="1" src="./img/new-vision-01.jpg">
                       <img alt="2" src="./img/vision1.jpg">  -->
                       
                       
                       
                  <figure class="figure" >
						  <img src="./img/bgfirst.jpg" class="figure-img img-fluid rounded" alt="..." id="bgfirst">
						 <!--  <figcaption class="figure-caption">A caption for the above image.</figcaption> -->
						</figure>
						<figure class="figure" >
						  <img src="./img/bgsecond.jpg" class="figure-img img-fluid rounded" alt="..." id="bgfirst">
						 <!--  <figcaption class="figure-caption">A caption for the above image.</figcaption> -->
						</figure>
						  <figure class="figure">
						  <img src="./img/bgthird.jpg" class="figure-img img-fluid rounded" alt="...">
						 <!--  <figcaption class="figure-caption">A caption for the above image.</figcaption> -->
						</figure> 
                      
                       </div>
                </div>        
            </div>
        </div>
        
<!-- Main -->
        <main>
            <!-- Welcome section -->
            <section class="tm-welcome">
                <div class="row">
                    <div class="col-12">
                        <h2 class="tm-section-header tm-header-floating">Welcome to WasteMart</h2>         
                    </div>
                </div>
                
                <div class="row tm-welcome-row">
                    <article class="col-lg-6 tm-media">
                        <img src="img/09.jpg" alt="Welcome image" class="img-fluid tm-media-img" />
                        <div class="tm-media-body">
                            <a href="#" class="tm-article-link"><h3 class="tm-article-title text-uppercase">Scrap Paper</h3></a>
                            <p>The Paper Waste generated by newspapers or books !! Do not worry we are here to help.</p>
                        </div>
                    </article>
                    <article class="col-lg-6 tm-media">
                        <img src="img/3.jpg" alt="Welcome image" class="img-fluid tm-media-img" style="height:200px" />
                        <div class="tm-media-body">
                            <a href="#" class="tm-article-link"><h3 class="tm-article-title text-uppercase">Plastic Waste</h3></a>
                            <p>Different Plastic waste generated ! Do not worry we here there to handle.</p>
                        </div>
                    </article>
                    <article class="col-lg-6 tm-media">
                        <img src="img/03.jpg" alt="Welcome image" class="img-fluid tm-media-img" />
                        <div class="tm-media-body">
                            <a href="#" class="tm-article-link"><h3 class="tm-article-title text-uppercase">Metal and other Waste</h3></a>
                            <p>Metals and different categories of waste ! Here we are in your help</p>
                        </div>
                    </article>
                    <article class="col-lg-6 tm-media">
                        <img src="img/2.jpg" alt="Welcome image" class="img-fluid tm-media-img" />
                        <div class="tm-media-body">
                            <a href="#" class="tm-article-link"><h3 class="tm-article-title text-uppercase">Wastes</h3></a>
                            <p>Please tell your friends about TemplateMo website. Thank you. Title / Text #666</p>
                        </div>
                    </article>
                </div>
                
                <div class="row">
                    <div class="col-12">
                        <h2 class="tm-section-header tm-section-header-small">Customer Feedback</h2>        
                    </div>
                </div><br/><br/>
                
                <div class="row tm-welcome-row-2">
                    <div class="col-lg-4 tm-dotted-box-container">
                        <article class="tm-dotted-box">
<!--                             <i class="fas fa-3x fa-binoculars tm-article-icon"></i> -->
                           <img src="img/new-vision-03.jpg" alt="alternate"><br/>
                            <h3 class="tm-article-title">Kathan Modi</h3>
                            <p class="tm-article-text">Great Service and Good idea to digitalize the least explored space - "waste" .Had great experience working with team </p>
                           
                        </article>    
                    </div>
                    <div class="col-lg-4 tm-dotted-box-container">
                        <article class="tm-dotted-box">
                            <!-- <i class="fas fa-3x fa-microscope tm-article-icon"></i> -->
                             <img src="img/new-vision-04.jpg" alt="alternate"><br/>
                            <h3 class="tm-article-title">Yashil Jogi</h3>
                            <p class="tm-article-text">Good Service , will surely continue using this and also suggest my friends to use this.</p>
                        </article>    
                    </div>
                    <div class="col-lg-4 tm-dotted-box-container">
                        <article class="tm-dotted-box">
                         <!--    <i class="fas fa-3x fa-glasses tm-article-icon"></i> -->
                          <img src="img/new-vision-02.jpg" alt="alternate"><br/>
                            <h3 class="tm-article-title">Rahul Sanghavi</h3>
                            <p class="tm-article-text">Do not think twice just use this webapp and enjoy and good service and customer relation.</p>
                            
                        </article>
                    </div>
                </div>
            </section>
           
            <!-- Featured -->
           <!--  <section class="tm-featured"> 
                <div class="row">
                    <div class="col-12">
                        <h2 class="tm-section-header tm-section-header-small">Featured All Scrap and waste Items</h2>        
                    </div>
                </div>
                
                Carousel
                <div class="grid tm-carousel">
                <figure class="effect-honey">
                        <img src="img/02.jpg" alt="Featured Item">
                        <figcaption>
                            <h4><i><span>Best</span> Paper scrap</i></h4>
                        </figcaption>
                    </figure>
                    <figure class="effect-honey">
                        <img src="img/03.jpg" alt="Featured Item">
                        <figcaption>
                            <h4><i><span>Best</span> Metal scrap</i></h4>
                        </figcaption>
                    </figure>
                    <figure class="effect-honey">
                        <img src="img/04.jpg" alt="Featured Item">
                        <figcaption>
                            <h4><i><span>Top</span>Plastic waste</i></h4>
                        </figcaption>
                    </figure>
                    <figure class="effect-honey">
                        <img src="img/05.jfif" alt="Featured Item">
                        <figcaption>
                            <h4><i><span>Best</span> Paper and metal</i></h4>
                        </figcaption>
                    </figure>
                    <figure class="effect-honey">
                        <img src="img/06.jfif" alt="Featured Item">
                        <figcaption>
                            <h4><i><span>Great</span> Newspaper Collection</i></h4>
                        </figcaption>
                    </figure>
                    <figure class="effect-honey">
                        <img src="img/07.jfif" alt="Featured Item">
                        <figcaption>
                            <h4><i><span>Best</span> Reduce Reuse</i></h4>
                        </figcaption>
                    </figure>
                    <figure class="effect-honey">
                        <img src="img/08.jpg" alt="Featured Item">
                        <figcaption>
                            <h4><i><span>Max</span> Paper Scrap</i></h4>
                        </figcaption>
                    </figure>
                    <figure class="effect-honey">
                        <img src="img/09.jpg" alt="Featured Item">
                        <figcaption>
                            <h4><i><span>Best</span>Newspaper pasti</i></h4>
                        </figcaption>
                    </figure>
                    
                </div>
            </section> -->
            </main>
            
</body>
</html>